name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install required packages
      run: sudo apt install -y make python3-venv
    - name: setup dev env
      run: make dev
    - name: run testing
      run: make tests
